// Package fb contains FlatBuffers-generated code for the blob index format.
//
// This package is auto-generated by the FlatBuffers compiler. Do not edit directly.
// Regenerate using: flatc --go --go-namespace fb -o internal schema/index.fbs
package fb
