// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import "strconv"

type HashAlgorithm int8

const (
	HashAlgorithmSHA256 HashAlgorithm = 0
)

var EnumNamesHashAlgorithm = map[HashAlgorithm]string{
	HashAlgorithmSHA256: "SHA256",
}

var EnumValuesHashAlgorithm = map[string]HashAlgorithm{
	"SHA256": HashAlgorithmSHA256,
}

func (v HashAlgorithm) String() string {
	if s, ok := EnumNamesHashAlgorithm[v]; ok {
		return s
	}
	return "HashAlgorithm(" + strconv.FormatInt(int64(v), 10) + ")"
}
