// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"io"
	"net/http"
	"sync"

	ocispec "github.com/opencontainers/image-spec/specs-go/v1"

	"github.com/meigma/blob/registry"
)

// Ensure, that OCIClientMock does implement registry.OCIClient.
// If this is not the case, regenerate this file with moq.
var _ registry.OCIClient = &OCIClientMock{}

// OCIClientMock is a mock implementation of client.OCIClient.
//
//	func TestSomethingThatUsesOCIClient(t *testing.T) {
//
//		// make and configure a mocked client.OCIClient
//		mockedOCIClient := &OCIClientMock{
//			AuthHeadersFunc: func(ctx context.Context, repoRef string) (http.Header, error) {
//				panic("mock out the AuthHeaders method")
//			},
//			BlobURLFunc: func(repoRef string, digest string) (string, error) {
//				panic("mock out the BlobURL method")
//			},
//			FetchBlobFunc: func(ctx context.Context, repoRef string, desc *ocispec.Descriptor) (io.ReadCloser, error) {
//				panic("mock out the FetchBlob method")
//			},
//			FetchManifestFunc: func(ctx context.Context, repoRef string, expected *ocispec.Descriptor) (ocispec.Manifest, []byte, error) {
//				panic("mock out the FetchManifest method")
//			},
//			InvalidateAuthHeadersFunc: func(repoRef string) error {
//				panic("mock out the InvalidateAuthHeaders method")
//			},
//			PushBlobFunc: func(ctx context.Context, repoRef string, desc *ocispec.Descriptor, r io.Reader) error {
//				panic("mock out the PushBlob method")
//			},
//			PushManifestFunc: func(ctx context.Context, repoRef string, tag string, manifest *ocispec.Manifest) (ocispec.Descriptor, error) {
//				panic("mock out the PushManifest method")
//			},
//			ResolveFunc: func(ctx context.Context, repoRef string, ref string) (ocispec.Descriptor, error) {
//				panic("mock out the Resolve method")
//			},
//			TagFunc: func(ctx context.Context, repoRef string, desc *ocispec.Descriptor, tag string) error {
//				panic("mock out the Tag method")
//			},
//		}
//
//		// use mockedOCIClient in code that requires client.OCIClient
//		// and then make assertions.
//
//	}
type OCIClientMock struct {
	// AuthHeadersFunc mocks the AuthHeaders method.
	AuthHeadersFunc func(ctx context.Context, repoRef string) (http.Header, error)

	// BlobURLFunc mocks the BlobURL method.
	BlobURLFunc func(repoRef string, digest string) (string, error)

	// FetchBlobFunc mocks the FetchBlob method.
	FetchBlobFunc func(ctx context.Context, repoRef string, desc *ocispec.Descriptor) (io.ReadCloser, error)

	// FetchManifestFunc mocks the FetchManifest method.
	FetchManifestFunc func(ctx context.Context, repoRef string, expected *ocispec.Descriptor) (ocispec.Manifest, []byte, error)

	// InvalidateAuthHeadersFunc mocks the InvalidateAuthHeaders method.
	InvalidateAuthHeadersFunc func(repoRef string) error

	// PushBlobFunc mocks the PushBlob method.
	PushBlobFunc func(ctx context.Context, repoRef string, desc *ocispec.Descriptor, r io.Reader) error

	// PushManifestFunc mocks the PushManifest method.
	PushManifestFunc func(ctx context.Context, repoRef string, tag string, manifest *ocispec.Manifest) (ocispec.Descriptor, error)

	// ResolveFunc mocks the Resolve method.
	ResolveFunc func(ctx context.Context, repoRef string, ref string) (ocispec.Descriptor, error)

	// TagFunc mocks the Tag method.
	TagFunc func(ctx context.Context, repoRef string, desc *ocispec.Descriptor, tag string) error

	// calls tracks calls to the methods.
	calls struct {
		// AuthHeaders holds details about calls to the AuthHeaders method.
		AuthHeaders []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoRef is the repoRef argument value.
			RepoRef string
		}
		// BlobURL holds details about calls to the BlobURL method.
		BlobURL []struct {
			// RepoRef is the repoRef argument value.
			RepoRef string
			// Digest is the digest argument value.
			Digest string
		}
		// FetchBlob holds details about calls to the FetchBlob method.
		FetchBlob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoRef is the repoRef argument value.
			RepoRef string
			// Desc is the desc argument value.
			Desc *ocispec.Descriptor
		}
		// FetchManifest holds details about calls to the FetchManifest method.
		FetchManifest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoRef is the repoRef argument value.
			RepoRef string
			// Expected is the expected argument value.
			Expected *ocispec.Descriptor
		}
		// InvalidateAuthHeaders holds details about calls to the InvalidateAuthHeaders method.
		InvalidateAuthHeaders []struct {
			// RepoRef is the repoRef argument value.
			RepoRef string
		}
		// PushBlob holds details about calls to the PushBlob method.
		PushBlob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoRef is the repoRef argument value.
			RepoRef string
			// Desc is the desc argument value.
			Desc *ocispec.Descriptor
			// R is the r argument value.
			R io.Reader
		}
		// PushManifest holds details about calls to the PushManifest method.
		PushManifest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoRef is the repoRef argument value.
			RepoRef string
			// Tag is the tag argument value.
			Tag string
			// Manifest is the manifest argument value.
			Manifest *ocispec.Manifest
		}
		// Resolve holds details about calls to the Resolve method.
		Resolve []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoRef is the repoRef argument value.
			RepoRef string
			// Ref is the ref argument value.
			Ref string
		}
		// Tag holds details about calls to the Tag method.
		Tag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoRef is the repoRef argument value.
			RepoRef string
			// Desc is the desc argument value.
			Desc *ocispec.Descriptor
			// Tag is the tag argument value.
			Tag string
		}
	}
	lockAuthHeaders           sync.RWMutex
	lockBlobURL               sync.RWMutex
	lockFetchBlob             sync.RWMutex
	lockFetchManifest         sync.RWMutex
	lockInvalidateAuthHeaders sync.RWMutex
	lockPushBlob              sync.RWMutex
	lockPushManifest          sync.RWMutex
	lockResolve               sync.RWMutex
	lockTag                   sync.RWMutex
}

// AuthHeaders calls AuthHeadersFunc.
func (mock *OCIClientMock) AuthHeaders(ctx context.Context, repoRef string) (http.Header, error) {
	if mock.AuthHeadersFunc == nil {
		panic("OCIClientMock.AuthHeadersFunc: method is nil but OCIClient.AuthHeaders was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		RepoRef string
	}{
		Ctx:     ctx,
		RepoRef: repoRef,
	}
	mock.lockAuthHeaders.Lock()
	mock.calls.AuthHeaders = append(mock.calls.AuthHeaders, callInfo)
	mock.lockAuthHeaders.Unlock()
	return mock.AuthHeadersFunc(ctx, repoRef)
}

// AuthHeadersCalls gets all the calls that were made to AuthHeaders.
// Check the length with:
//
//	len(mockedOCIClient.AuthHeadersCalls())
func (mock *OCIClientMock) AuthHeadersCalls() []struct {
	Ctx     context.Context
	RepoRef string
} {
	var calls []struct {
		Ctx     context.Context
		RepoRef string
	}
	mock.lockAuthHeaders.RLock()
	calls = mock.calls.AuthHeaders
	mock.lockAuthHeaders.RUnlock()
	return calls
}

// BlobURL calls BlobURLFunc.
func (mock *OCIClientMock) BlobURL(repoRef string, digest string) (string, error) {
	if mock.BlobURLFunc == nil {
		panic("OCIClientMock.BlobURLFunc: method is nil but OCIClient.BlobURL was just called")
	}
	callInfo := struct {
		RepoRef string
		Digest  string
	}{
		RepoRef: repoRef,
		Digest:  digest,
	}
	mock.lockBlobURL.Lock()
	mock.calls.BlobURL = append(mock.calls.BlobURL, callInfo)
	mock.lockBlobURL.Unlock()
	return mock.BlobURLFunc(repoRef, digest)
}

// BlobURLCalls gets all the calls that were made to BlobURL.
// Check the length with:
//
//	len(mockedOCIClient.BlobURLCalls())
func (mock *OCIClientMock) BlobURLCalls() []struct {
	RepoRef string
	Digest  string
} {
	var calls []struct {
		RepoRef string
		Digest  string
	}
	mock.lockBlobURL.RLock()
	calls = mock.calls.BlobURL
	mock.lockBlobURL.RUnlock()
	return calls
}

// FetchBlob calls FetchBlobFunc.
func (mock *OCIClientMock) FetchBlob(ctx context.Context, repoRef string, desc *ocispec.Descriptor) (io.ReadCloser, error) {
	if mock.FetchBlobFunc == nil {
		panic("OCIClientMock.FetchBlobFunc: method is nil but OCIClient.FetchBlob was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		RepoRef string
		Desc    *ocispec.Descriptor
	}{
		Ctx:     ctx,
		RepoRef: repoRef,
		Desc:    desc,
	}
	mock.lockFetchBlob.Lock()
	mock.calls.FetchBlob = append(mock.calls.FetchBlob, callInfo)
	mock.lockFetchBlob.Unlock()
	return mock.FetchBlobFunc(ctx, repoRef, desc)
}

// FetchBlobCalls gets all the calls that were made to FetchBlob.
// Check the length with:
//
//	len(mockedOCIClient.FetchBlobCalls())
func (mock *OCIClientMock) FetchBlobCalls() []struct {
	Ctx     context.Context
	RepoRef string
	Desc    *ocispec.Descriptor
} {
	var calls []struct {
		Ctx     context.Context
		RepoRef string
		Desc    *ocispec.Descriptor
	}
	mock.lockFetchBlob.RLock()
	calls = mock.calls.FetchBlob
	mock.lockFetchBlob.RUnlock()
	return calls
}

// FetchManifest calls FetchManifestFunc.
func (mock *OCIClientMock) FetchManifest(ctx context.Context, repoRef string, expected *ocispec.Descriptor) (ocispec.Manifest, []byte, error) {
	if mock.FetchManifestFunc == nil {
		panic("OCIClientMock.FetchManifestFunc: method is nil but OCIClient.FetchManifest was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		RepoRef  string
		Expected *ocispec.Descriptor
	}{
		Ctx:      ctx,
		RepoRef:  repoRef,
		Expected: expected,
	}
	mock.lockFetchManifest.Lock()
	mock.calls.FetchManifest = append(mock.calls.FetchManifest, callInfo)
	mock.lockFetchManifest.Unlock()
	return mock.FetchManifestFunc(ctx, repoRef, expected)
}

// FetchManifestCalls gets all the calls that were made to FetchManifest.
// Check the length with:
//
//	len(mockedOCIClient.FetchManifestCalls())
func (mock *OCIClientMock) FetchManifestCalls() []struct {
	Ctx      context.Context
	RepoRef  string
	Expected *ocispec.Descriptor
} {
	var calls []struct {
		Ctx      context.Context
		RepoRef  string
		Expected *ocispec.Descriptor
	}
	mock.lockFetchManifest.RLock()
	calls = mock.calls.FetchManifest
	mock.lockFetchManifest.RUnlock()
	return calls
}

// InvalidateAuthHeaders calls InvalidateAuthHeadersFunc.
func (mock *OCIClientMock) InvalidateAuthHeaders(repoRef string) error {
	if mock.InvalidateAuthHeadersFunc == nil {
		panic("OCIClientMock.InvalidateAuthHeadersFunc: method is nil but OCIClient.InvalidateAuthHeaders was just called")
	}
	callInfo := struct {
		RepoRef string
	}{
		RepoRef: repoRef,
	}
	mock.lockInvalidateAuthHeaders.Lock()
	mock.calls.InvalidateAuthHeaders = append(mock.calls.InvalidateAuthHeaders, callInfo)
	mock.lockInvalidateAuthHeaders.Unlock()
	return mock.InvalidateAuthHeadersFunc(repoRef)
}

// InvalidateAuthHeadersCalls gets all the calls that were made to InvalidateAuthHeaders.
// Check the length with:
//
//	len(mockedOCIClient.InvalidateAuthHeadersCalls())
func (mock *OCIClientMock) InvalidateAuthHeadersCalls() []struct {
	RepoRef string
} {
	var calls []struct {
		RepoRef string
	}
	mock.lockInvalidateAuthHeaders.RLock()
	calls = mock.calls.InvalidateAuthHeaders
	mock.lockInvalidateAuthHeaders.RUnlock()
	return calls
}

// PushBlob calls PushBlobFunc.
func (mock *OCIClientMock) PushBlob(ctx context.Context, repoRef string, desc *ocispec.Descriptor, r io.Reader) error {
	if mock.PushBlobFunc == nil {
		panic("OCIClientMock.PushBlobFunc: method is nil but OCIClient.PushBlob was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		RepoRef string
		Desc    *ocispec.Descriptor
		R       io.Reader
	}{
		Ctx:     ctx,
		RepoRef: repoRef,
		Desc:    desc,
		R:       r,
	}
	mock.lockPushBlob.Lock()
	mock.calls.PushBlob = append(mock.calls.PushBlob, callInfo)
	mock.lockPushBlob.Unlock()
	return mock.PushBlobFunc(ctx, repoRef, desc, r)
}

// PushBlobCalls gets all the calls that were made to PushBlob.
// Check the length with:
//
//	len(mockedOCIClient.PushBlobCalls())
func (mock *OCIClientMock) PushBlobCalls() []struct {
	Ctx     context.Context
	RepoRef string
	Desc    *ocispec.Descriptor
	R       io.Reader
} {
	var calls []struct {
		Ctx     context.Context
		RepoRef string
		Desc    *ocispec.Descriptor
		R       io.Reader
	}
	mock.lockPushBlob.RLock()
	calls = mock.calls.PushBlob
	mock.lockPushBlob.RUnlock()
	return calls
}

// PushManifest calls PushManifestFunc.
func (mock *OCIClientMock) PushManifest(ctx context.Context, repoRef string, tag string, manifest *ocispec.Manifest) (ocispec.Descriptor, error) {
	if mock.PushManifestFunc == nil {
		panic("OCIClientMock.PushManifestFunc: method is nil but OCIClient.PushManifest was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		RepoRef  string
		Tag      string
		Manifest *ocispec.Manifest
	}{
		Ctx:      ctx,
		RepoRef:  repoRef,
		Tag:      tag,
		Manifest: manifest,
	}
	mock.lockPushManifest.Lock()
	mock.calls.PushManifest = append(mock.calls.PushManifest, callInfo)
	mock.lockPushManifest.Unlock()
	return mock.PushManifestFunc(ctx, repoRef, tag, manifest)
}

// PushManifestCalls gets all the calls that were made to PushManifest.
// Check the length with:
//
//	len(mockedOCIClient.PushManifestCalls())
func (mock *OCIClientMock) PushManifestCalls() []struct {
	Ctx      context.Context
	RepoRef  string
	Tag      string
	Manifest *ocispec.Manifest
} {
	var calls []struct {
		Ctx      context.Context
		RepoRef  string
		Tag      string
		Manifest *ocispec.Manifest
	}
	mock.lockPushManifest.RLock()
	calls = mock.calls.PushManifest
	mock.lockPushManifest.RUnlock()
	return calls
}

// Resolve calls ResolveFunc.
func (mock *OCIClientMock) Resolve(ctx context.Context, repoRef string, ref string) (ocispec.Descriptor, error) {
	if mock.ResolveFunc == nil {
		panic("OCIClientMock.ResolveFunc: method is nil but OCIClient.Resolve was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		RepoRef string
		Ref     string
	}{
		Ctx:     ctx,
		RepoRef: repoRef,
		Ref:     ref,
	}
	mock.lockResolve.Lock()
	mock.calls.Resolve = append(mock.calls.Resolve, callInfo)
	mock.lockResolve.Unlock()
	return mock.ResolveFunc(ctx, repoRef, ref)
}

// ResolveCalls gets all the calls that were made to Resolve.
// Check the length with:
//
//	len(mockedOCIClient.ResolveCalls())
func (mock *OCIClientMock) ResolveCalls() []struct {
	Ctx     context.Context
	RepoRef string
	Ref     string
} {
	var calls []struct {
		Ctx     context.Context
		RepoRef string
		Ref     string
	}
	mock.lockResolve.RLock()
	calls = mock.calls.Resolve
	mock.lockResolve.RUnlock()
	return calls
}

// Tag calls TagFunc.
func (mock *OCIClientMock) Tag(ctx context.Context, repoRef string, desc *ocispec.Descriptor, tag string) error {
	if mock.TagFunc == nil {
		panic("OCIClientMock.TagFunc: method is nil but OCIClient.Tag was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		RepoRef string
		Desc    *ocispec.Descriptor
		Tag     string
	}{
		Ctx:     ctx,
		RepoRef: repoRef,
		Desc:    desc,
		Tag:     tag,
	}
	mock.lockTag.Lock()
	mock.calls.Tag = append(mock.calls.Tag, callInfo)
	mock.lockTag.Unlock()
	return mock.TagFunc(ctx, repoRef, desc, tag)
}

// TagCalls gets all the calls that were made to Tag.
// Check the length with:
//
//	len(mockedOCIClient.TagCalls())
func (mock *OCIClientMock) TagCalls() []struct {
	Ctx     context.Context
	RepoRef string
	Desc    *ocispec.Descriptor
	Tag     string
} {
	var calls []struct {
		Ctx     context.Context
		RepoRef string
		Desc    *ocispec.Descriptor
		Tag     string
	}
	mock.lockTag.RLock()
	calls = mock.calls.Tag
	mock.lockTag.RUnlock()
	return calls
}
