// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	"bytes"
	flatbuffers "github.com/google/flatbuffers/go"
)

type Entry struct {
	_tab flatbuffers.Table
}

func GetRootAsEntry(buf []byte, offset flatbuffers.UOffsetT) *Entry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Entry{}
	x.Init(buf, n+offset)
	return x
}

func FinishEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEntry(buf []byte, offset flatbuffers.UOffsetT) *Entry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Entry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Entry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Entry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Entry) Path() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func EntryKeyCompare(o1, o2 flatbuffers.UOffsetT, buf []byte) bool {
	obj1 := &Entry{}
	obj2 := &Entry{}
	obj1.Init(buf, flatbuffers.UOffsetT(len(buf))-o1)
	obj2.Init(buf, flatbuffers.UOffsetT(len(buf))-o2)
	return string(obj1.Path()) < string(obj2.Path())
}

func (rcv *Entry) LookupByKey(key string, vectorLocation flatbuffers.UOffsetT, buf []byte) bool {
	span := flatbuffers.GetUOffsetT(buf[vectorLocation-4:])
	start := flatbuffers.UOffsetT(0)
	bKey := []byte(key)
	for span != 0 {
		middle := span / 2
		tableOffset := flatbuffers.GetIndirectOffset(buf, vectorLocation+4*(start+middle))
		obj := &Entry{}
		obj.Init(buf, tableOffset)
		comp := bytes.Compare(obj.Path(), bKey)
		if comp > 0 {
			span = middle
		} else if comp < 0 {
			middle += 1
			start += middle
			span -= middle
		} else {
			rcv.Init(buf, tableOffset)
			return true
		}
	}
	return false
}

func (rcv *Entry) DataOffset() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Entry) MutateDataOffset(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *Entry) DataSize() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Entry) MutateDataSize(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *Entry) OriginalSize() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Entry) MutateOriginalSize(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *Entry) Hash(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Entry) HashLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Entry) HashBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Entry) MutateHash(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *Entry) Mode() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Entry) MutateMode(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

func (rcv *Entry) Uid() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Entry) MutateUid(n uint32) bool {
	return rcv._tab.MutateUint32Slot(16, n)
}

func (rcv *Entry) Gid() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Entry) MutateGid(n uint32) bool {
	return rcv._tab.MutateUint32Slot(18, n)
}

func (rcv *Entry) MtimeNs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Entry) MutateMtimeNs(n int64) bool {
	return rcv._tab.MutateInt64Slot(20, n)
}

func (rcv *Entry) Compression() Compression {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return Compression(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Entry) MutateCompression(n Compression) bool {
	return rcv._tab.MutateInt8Slot(22, int8(n))
}

func EntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func EntryAddPath(builder *flatbuffers.Builder, path flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(path), 0)
}
func EntryAddDataOffset(builder *flatbuffers.Builder, dataOffset uint64) {
	builder.PrependUint64Slot(1, dataOffset, 0)
}
func EntryAddDataSize(builder *flatbuffers.Builder, dataSize uint64) {
	builder.PrependUint64Slot(2, dataSize, 0)
}
func EntryAddOriginalSize(builder *flatbuffers.Builder, originalSize uint64) {
	builder.PrependUint64Slot(3, originalSize, 0)
}
func EntryAddHash(builder *flatbuffers.Builder, hash flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(hash), 0)
}
func EntryStartHashVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func EntryAddMode(builder *flatbuffers.Builder, mode uint32) {
	builder.PrependUint32Slot(5, mode, 0)
}
func EntryAddUid(builder *flatbuffers.Builder, uid uint32) {
	builder.PrependUint32Slot(6, uid, 0)
}
func EntryAddGid(builder *flatbuffers.Builder, gid uint32) {
	builder.PrependUint32Slot(7, gid, 0)
}
func EntryAddMtimeNs(builder *flatbuffers.Builder, mtimeNs int64) {
	builder.PrependInt64Slot(8, mtimeNs, 0)
}
func EntryAddCompression(builder *flatbuffers.Builder, compression Compression) {
	builder.PrependInt8Slot(9, int8(compression), 0)
}
func EntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
