// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatbuffers

import "strconv"

type Compression int8

const (
	CompressionNone Compression = 0
	CompressionZstd Compression = 1
)

var EnumNamesCompression = map[Compression]string{
	CompressionNone: "None",
	CompressionZstd: "Zstd",
}

var EnumValuesCompression = map[string]Compression{
	"None": CompressionNone,
	"Zstd": CompressionZstd,
}

func (v Compression) String() string {
	if s, ok := EnumNamesCompression[v]; ok {
		return s
	}
	return "Compression(" + strconv.FormatInt(int64(v), 10) + ")"
}
